### ISSUE TITLE
不好意思，这项测试很难让我不当真...

### ISSUE THREAD

**Issue by fr1g** [jj11hh/yavt.fengtao.xyz#2]
您的0.2.1题库中有很多有歧义的、回答导向绝对的题目。由于数量较多，不一一列举。
最后，您的结果页面的用词让我感受到了蓝色正在不怀好意地渗透。
由此我建议您对结果页面稍作改动：
把“权威”改为“约束”，把“威权主义”改为“偏向秩序”。----这个词就很精妙，举例说美国是个自由的国度，为了实现牛津词典上的自由释义，美国的秩序体系相对中国来说要弱一些；中国基于“不加限制的自由必会带来强者对弱者的剥削”制定的秩序体系相对于美国来说更严苛，更稳定，同时，两国人民除了“听到现实生活中的枪声的几率”有极大差别，别的生活质量好像差不多，甚至中国人更有幸福感。
当然，香港特别行政区和台湾省我不太清楚，但是这两地犯下的错终会被社会历史的主体来修复。
一切为了人民。

**Comment by jj11hh** [comment]
你好，这个repo fork自一个已经消失的项目，词汇翻译自
8values.github.io
和
9axes.github.io
因为这些词汇和题目大多是翻译的，所以可能有不尽人意之处。但是这个世界是发展的，可能现在有不足，总处于一个螺旋上升的状态。我本人不是这些文本的作者，且不擅文辞。如果有人能够翻译出加好的文本，我会把它更新在这里。
